### PR TITLE
fix(performance): pre-compute and lazily initialize endpoint methods

### PR DESCRIPTION
**Pull request by ZauberNerd**
We have observed that the octokit initialisation is quite slow,
especially in combination with [probots](https://github.com/probot/probot)
which creates a new octokit instance for each incoming request.
This causes the main event loop to block for a considerable time.

With our change we moved the preparation of the endpoints api object
into the module scope and use a Proxy object to defer the initialisation
of octokit defaults and decorations to the first API call per method.

Although we have not measured it, we believe the overhead that comes
from the proxied method call is insignificant in comparison to the
network latency of an API call.

---

We have profiled our change with a flamegraph generated with [Clinic.js](https://clinicjs.org/).
The two screenshots below show the before and after state of 10k octokit initialisations:
```js
for (let i = 0; i < 10000; i++) {
  const MyOctokit = Octokit.plugin(restEndpointMethods);
  const octokit = new MyOctokit({
    auth: `personal-access-token123`,
  });
}
```

**Before**
Screenshot from 2023-03-08 11-57-17

**After**
Screenshot from 2023-03-08 11-56-23

### CODE REVIEW

**Review by gr2m — DISMISSED** [review]
Fascinating. I didn't have a chance to use Proxies yet, but I think the usage makes a lot of sense here. I'm always reluctant about internal caching like this because the first call of the method behaves different then the second call, and if there is rare error condition it's very hard to debug. But given that in this package the methods are very monotonous, and the improvement quite significant, I think it's worth it.

Could you please add a comment with a short description of how it works and why this optimization was done, with a reference to this pull request?

**Comment by gr2m** [comment]
> Could you please add a comment with a short description of how it works and why this optimization was done, with a reference to this pull request?

@ZauberNerd could you do that please? No worries if not, I'd say we can add that ourselves and merge the PR

**Comment by ZauberNerd** [comment]
@gr2m sorry for the delay. I've added a comment and fixed a typo (`enpointMethodsMap` => `endpointMethodsMap`).

**Comment by gr2m** [comment]
Thanks @ZauberNerd! The new release should be out any moment. It will be a fix release so if you reset your lock file you should get the update. Let us know if it all works as expected

**Comment by ZauberNerd** [comment]
> Thanks @ZauberNerd! The new release should be out any moment. It will be a fix release so if you reset your lock file you should get the update. Let us know if it all works as expected

I'm using this in a probot setup and probot is still on v5 of this dependency.
But I have been running this change via patch-package for a few months now and so far seen no problems.

**Pull request merged**
