### PR TITLE
build: update template to use type imports

### PR DESCRIPTION
**Pull request by wolfy1339**
The changes were already made in the generated output. This doesn't make any further changes

Resolves #ISSUE_NUMBER

----

### Before the change?

* The template didn't include the change made to the import

### After the change?

* The template now includes the change made to the import

### Other information

*

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Comment by ollie-iterators** [comment]
This PR is needed for https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/647

**Comment by wolfy1339** [comment]
I can just merge this into #647 to unblock it. It'll be the quickest way to get it unblocked

**Comment by wolfy1339** [comment]
I can just merge this into #647 to unblock it. It'll be the quickest way to get it unblocked

**Comment by wolfy1339** [comment]
Done.

**Pull request closed without merging**
