### PR TITLE
fix: revert "feat: many unreleased updates to endpoint methods (#607)"

### PR DESCRIPTION
**Pull request by wolfy1339**
This reverts commit 1e9bf6893ad36eaa6e099f1dfd964b7cd965c214.

----

### Before the change?

* Breaking changes were introduced in a feature version

### After the change?

* The breaking changes will be reverted

### Other information

*

----

### Pull request checklist
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Added the appropriate label for the given change

### Does this introduce a breaking change?

Please see our docs on [breaking changes](https://github.com/octokit/.github/blob/main/community/breaking_changes.md) to help!

- [ ] Yes (Please add the `Type: Breaking change` label)
- [x] No

If `Yes`, what's the impact:

* N/A

### Pull request type

Please add the corresponding label for change this PR introduces:
- Bugfix: `Type: Bug`
- Feature/model/API additions: `Type: Feature`
- Updates to docs or samples: `Type: Documentation`
- Dependencies/code cleanup: `Type: Maintenance`

----

### CODE REVIEW

**Review by kfcampbell — APPROVED** [review]

**Comment by wolfy1339** [comment]
I think there's something wrong with the required tests in this repo.
There's 2 tests that no longer exist, and haven't existed for a while now marked as required.

The `Test / test` workflow should be the one set to be required

**Comment by wolfy1339** [comment]
It seems to only have happened on this PR

**Comment by kfcampbell** [comment]
That's bizarre. I don't see any differences in the workflows between these two branches and main. I'm not aware of any configuration options we can tweak in the Actions tab.

**Comment by wolfy1339** [comment]
I have no idea either. You should be able to merge it anyways as an admin

**Comment by kfcampbell** [comment]
Sure, I've done so now.

**Pull request merged**
