### PR TITLE
ci: stop testing against NodeJS v14, v16

### PR DESCRIPTION
**Pull request by wolfy1339**
BREAKING CHANGE: Drop support for NodeJS v14, v16

### CODE REVIEW

**Review by kfcampbell — APPROVED** [review]

**Comment by nickfloyd** [comment]
https://github.com/orgs/octokit/discussions/44

**Comment by wolfy1339** [comment]
Branch protection rules nees to be fixed for the `beta` branch. It needs to point to the `test` job, and not the old ones which have node versions in their name

**Comment by wolfy1339** [comment]
Those steps look good

**Review by millermusk56 — COMMENTED** [review]
iCloud Passkeys

**Comment by millermusk56** [comment]
iPhone 16 passkeys

**Pull request merged**
